apiVersion: skaffold/v4beta6
kind: Config

build:
  artifacts:
    - image: user
      context: ./frontend/user/
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: ./frontend/user/Dockerfile
    - image: editor
      context: ./frontend/editor/
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: ./frontend/editor/dev.Dockerfile

manifests:
  helm:
    releases:
      - name: devwiki
        chartPath: ./helm
        valuesFiles:
          - ./helm/values-dev.yaml