apiVersion: skaffold/v4beta6
kind: Config

build:
  artifacts:
    - image: ui
      context: ./services/
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: ./services/dev.Dockerfile
        buildArgs:
          SERVICE: ui
    - image: editor
      context: ./frontend/editor/
      sync:
        infer:
          - '**/*'
      docker:
        dockerfile: ./frontend/editor/dev.Dockerfile
  local:
    useBuildkit: true
    concurrency: 1

manifests:
  helm:
    releases:
      - name: devwiki
        chartPath: ./helm
        valuesFiles:
          - ./helm/values-dev.yaml