{{ range .Values.services }}
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: {{.name}}
spec:
  hostnames:
    - {{ $.Values.hostname }}
  parentRefs:
    - name: cluster-gw
      namespace: networking
  rules:
    - backendRefs:
        - name: {{ .name }}
          port: 80
      matches:
        - path:
            type: PathPrefix
            value: {{ .path }}
{{ end }}