
hostname: dev.devwiki.io

services:
  - name: user
    image: user:latest
    path: /
    resources:
      limits:
        cpu: 1
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi